meiduo_mall/apps/areas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^areas/$', views.AreasView.as_view()),


]

meiduo_mall/apps/carts/urls.py
from django.conf.urls import url


from . import views


urlpatterns = [
    #购物车增删改查
    url(r'^carts/$',views.CartsView.as_view()),
    #购物车增删改查
    url(r'^carts/selection/$',views.CartSelectAllView.as_view()),
    #购物车增删改查
    url(r'^carts/simple/$',views.CartSimpleView.as_view()),



]

meiduo_mall/apps/goods/urls.py
from django.conf.urls import url

from . import views



urlpatterns = [
    #商品列表界面
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)/$',views.ListView.as_view()),
    #商品热销排行
    url(r'^hot/(?P<category_id>\d+)/$', views.HotGoodsView.as_view()),
    #商品详情界面
    url(r'^detail/(?P<sku_id>\d+)/$', views.DetailView.as_view()),
    #商品详情界面商品类别统计
    url(r'^visit/(?P<category_id>\d+)/$', views.DetailVisitView.as_view()),

]

meiduo_mall/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^search/',include('haystack.urls')),

    url(r'^', include('users.urls', namespace='users')),  # 用户模块

    url(r'^', include('verifications.urls', namespace='verifications')),  # 验证码模块

    url(r'^', include('contents.urls', namespace='contents')),  # 首页模块

    url(r'^', include('oauth.urls', namespace='oauth')),  # QQ模块

    url(r'^',include('areas.urls',namespace='areas')),#省市区模块

    url(r'^',include('goods.urls',namespace='goods')),#商品模块

    url(r'^', include('carts.urls', namespace='carts')),  # 购物车模块

    url(r'^', include('orders.urls', namespace='orders')),  # 订单模块

    url(r'^', include('payment.urls', namespace='payment')),  # 支付模块

    url('^meiduo_admin/', include('meiduo_admin.urls')),
]

meiduo_mall/apps/goods/models.py
from django.db import models


from meiduo_mall.utils.models import BaseModel
# Create your models here.


class GoodsCategory(BaseModel):
    """商品类别"""
    name = models.CharField(max_length=10, verbose_name='名称')
    parent = models.ForeignKey('self', related_name='subs', null=True, blank=True, on_delete=models.CASCADE, verbose_name='父类别')

    class Meta:
        db_table = 'tb_goods_category'
        verbose_name = '商品类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannelGroup(BaseModel):
    """商品频道组"""
    name = models.CharField(max_length=20, verbose_name='频道组名')

    class Meta:
        db_table = 'tb_channel_group'
        verbose_name = '商品频道组'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannel(BaseModel):
    """商品频道"""
    group = models.ForeignKey(GoodsChannelGroup, verbose_name='频道组名')
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='顶级商品类别')
    url = models.CharField(max_length=50, verbose_name='频道页面链接')
    sequence = models.IntegerField(verbose_name='组内顺序')

    class Meta:
        db_table = 'tb_goods_channel'
        verbose_name = '商品频道'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.category.name


class Brand(BaseModel):
    """品牌"""
    name = models.CharField(max_length=20, verbose_name='名称')
    logo = models.ImageField(verbose_name='Logo图片')
    first_letter = models.CharField(max_length=1, verbose_name='品牌首字母')

    class Meta:
        db_table = 'tb_brand'
        verbose_name = '品牌'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SPU(BaseModel):
    """商品SPU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, verbose_name='品牌')
    category1 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat1_spu', verbose_name='一级类别')
    category2 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat2_spu', verbose_name='二级类别')
    category3 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat3_spu', verbose_name='三级类别')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    desc_detail = models.TextField(default='', verbose_name='详细介绍')
    desc_pack = models.TextField(default='', verbose_name='包装信息')
    desc_service = models.TextField(default='', verbose_name='售后服务')

    class Meta:
        db_table = 'tb_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SKU(BaseModel):
    """商品SKU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    caption = models.CharField(max_length=100, verbose_name='副标题')
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, verbose_name='商品')
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, verbose_name='从属类别')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='单价')
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='进价')
    market_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='市场价')
    stock = models.IntegerField(default=0, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    is_launched = models.BooleanField(default=True, verbose_name='是否上架销售')
    default_image = models.ImageField(max_length=200, default='', null=True, blank=True, verbose_name='默认图片')

    class Meta:
        db_table = 'tb_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class SKUImage(BaseModel):
    """SKU图片"""
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='sku')
    image = models.ImageField(verbose_name='图片')

    class Meta:
        db_table = 'tb_sku_image'
        verbose_name = 'SKU图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.id)


class SPUSpecification(BaseModel):
    """商品SPU规格"""
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, related_name='specs', verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='规格名称')

    class Meta:
        db_table = 'tb_spu_specification'
        verbose_name = '商品SPU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)


class SpecificationOption(BaseModel):
    """规格选项"""
    spec = models.ForeignKey(SPUSpecification, related_name='options', on_delete=models.CASCADE, verbose_name='规格')
    value = models.CharField(max_length=20, verbose_name='选项值')

    class Meta:
        db_table = 'tb_specification_option'
        verbose_name = '规格选项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(BaseModel):
    """SKU具体规格"""
    sku = models.ForeignKey(SKU, related_name='specs', on_delete=models.CASCADE, verbose_name='sku')
    spec = models.ForeignKey(SPUSpecification, on_delete=models.PROTECT, verbose_name='规格名称')
    option = models.ForeignKey(SpecificationOption, on_delete=models.PROTECT, verbose_name='规格值')

    class Meta:
        db_table = 'tb_sku_specification'
        verbose_name = 'SKU规格'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)


class GoodsVisitCount(BaseModel):
    """统计分类商品访问量模型类"""
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='商品分类')
    count = models.IntegerField(verbose_name='访问量', default=0)
    date = models.DateField(auto_now_add=True, verbose_name='统计日期')

    class Meta:
        db_table = 'tb_goods_visit'
        verbose_name = '统计分类商品访问量'
        verbose_name_plural = verbose_name

meiduo_mall/apps/areas/views.py
from django.shortcuts import render
from django.views import View
from .models import Area
from django import http
from django.core.cache import cache


from meiduo_mall.utils.response_code import RETCODE
# Create your views here.

class AreasView(View):
    """省市区数据"""
    def get(self,request):

        #获取查询参数area_id
        area_id = request.GET.get('area_id')

        #判断area_id是否有值
        #如果area_id为None:代表要查询所有省的数据
        if area_id is None:
            # 先尝试去redis获取所有省的缓存数据
            province_list = cache.get('province_list')
            if province_list is None:

                province_qs = Area.objects.filter(parent=None)

                #用来装所有省的数据字典
                province_list = []
                # 遍历查询集,将里面的每一个模型转换成字典格式
                for province_model in province_qs:
                    province_list.append(
                        {'id': province_model.id,
                         'name' : province_model.name
                         })
                # 没有缓存,就设置缓存
                cache.set('province_list', province_list, 3600)
            return http.JsonResponse({'code': RETCODE.OK, 'errmsg': 'OK', 'province_list': province_list})

        else:
            # 先去缓存读写数据,如果缓存中没有再去mysql
            data_dict = cache.get('sub_area' + area_id)
            if data_dict is None:
                # 如果area_id有值: 代表查询指定area_id的下级所有行政区
                # sub_qs = Area.objects.filter(parent_id=area_id)
                parent_model = Area.objects.get(id=area_id)
                sub_qs = parent_model.subs.all()

                sub_list = [] # 包装所有下级行政区字典
                for sub_model in sub_qs:
                    sub_list.append(
                        {
                            'id' : sub_model.id,
                            'name' : sub_model.name,
                        }
                    )
                #包装要响应的数据
                data_dict = {
                    'id' : parent_model.id,
                    'name' : parent_model.name,
                    'subs' : sub_list
                }
                # 设置缓存
                cache.set('sub_area' + area_id, data_dict, 3600)
            return http.JsonResponse({'code':RETCODE.OK,'errmsg' : 'OK','sub_data':data_dict})

meiduo_mall/apps/contents/views.py
from django.shortcuts import render
from django.views import View


from .utils import get_categories
from .models import Content,ContentCategory

class IndexView(View):

    def get(self, request):

        #定义用来包装所有广告数据的大字典
        contents = {}
        #查询所有广告类别数据
        contents_cat_qs = ContentCategory.objects.all()
        for content_cat in contents_cat_qs:
            contents[content_cat.key] = content_cat.content_set.filter(status=True).order_by('sequence')

        #准备模型渲染数据
        context = {
            'categories': get_categories(),
            'contents' : contents

        }
        return render(request, 'index.html',context)

meiduo_mall/apps/goods/views.py
from django.shortcuts import render
from django.views import  View
from django import http
from django.core.paginator import Paginator,EmptyPage
from django.utils import timezone


from .models import GoodsCategory, SKU, GoodsVisitCount
from contents.utils import get_categories
from .utils import get_breadcrumb
from meiduo_mall.utils.response_code import RETCODE
# Create your views here.


class ListView(View):
    """商品列表界面"""

    def get(self,request,category_id,page_num):
        try:
            category = GoodsCategory.objects.get(id=category_id)
        except GoodsCategory.DoesNotExist:
            return http.HttpResponseForbidden('category_id不存在')

        #接收前端传入的sort = 'XXX'
        sort = request.GET.get('sort','default')

        if sort == 'price':
            sort_filed = '-price'
        elif sort == 'hot':
            sort_filed = '-sales'
        else:
            sort = 'default'
            sort_filed = 'create_time'

        #把当前三级类型下的所有要上架的sku拿到
        sku_qs = category.sku_set.filter(is_launched=True).order_by(sort_filed)
        #创建分页器 Paginator(要进行分页的所有数据,指定每页显示多少条数据)
        paginator = Paginator(sku_qs,5)
        try:
            #获取指定页的数据
            page_skus = paginator.page(page_num)
        except EmptyPage:
            return http.HttpResponseForbidden('非法请求')
        #获取总页数
        total_page = paginator.num_pages

        context = {
            'categories' : get_categories(),#商品类别数据
            'breadcrumb' : get_breadcrumb(category),#面包屑导航
            'sort' : sort,#排序字段
            'category' : category,#第三级分类
            'page_skus' : page_skus,#分页后的数据
            'total_page' : total_page,#总页数
            'page_num' : page_num,#当前页码
        }
        return render(request,'list.html',context)


class HotGoodsView(View):
    """获取热销商品"""

    def get(self,request,category_id):
        try:
            category =  GoodsCategory.objects.get(id=category_id)
        except GoodsCategory.DoesNotExist:
            return http.HttpResponseForbidden('category_id不存在')

        #查询当前指定三级类别销量最高的前两个商品
        sku_qs = category.sku_set.filter(is_launched=True).order_by('-sales')[:2]

        hot_skus = []
        #模型转字典
        for sku in sku_qs:
            hot_skus.append({
                'id' : sku.id,
                'name' : sku.name,
                'price' : sku.price,
                'default_image_url' : sku.default_image.url

            })
        #响应
        return http.JsonResponse({'code':RETCODE.OK,'errmsg':'OK','hot_skus':hot_skus})


class DetailView(View):

    def get(self, request, sku_id):

        try:
            sku = SKU.objects.get(id=sku_id)
        except SKU.DoesNotExist:
            return render(request, '404.html')

        category = sku.category  # 获取当前sku所对应的三级分类

        # 查询当前sku所对应的spu
        spu = sku.spu

        """1.准备当前商品的规格选项列表 [8, 11]"""
        # 获取出当前正显示的sku商品的规格选项id列表
        current_sku_spec_qs = sku.specs.order_by('spec_id')
        current_sku_option_ids = []  # [8, 11]
        for current_sku_spec in current_sku_spec_qs:
            current_sku_option_ids.append(current_sku_spec.option_id)

        """2.构造规格选择仓库
        {(8, 11): 3, (8, 12): 4, (9, 11): 5, (9, 12): 6, (10, 11): 7, (10, 12): 8}
        """
        # 构造规格选择仓库
        temp_sku_qs = spu.sku_set.all()  # 获取当前spu下的所有sku
        # 选项仓库大字典
        spec_sku_map = {}  # {(8, 11): 3, (8, 12): 4, (9, 11): 5, (9, 12): 6, (10, 11): 7, (10, 12): 8}
        for temp_sku in temp_sku_qs:
            # 查询每一个sku的规格数据
            temp_spec_qs = temp_sku.specs.order_by('spec_id')
            temp_sku_option_ids = []  # 用来包装每个sku的选项值
            for temp_spec in temp_spec_qs:
                temp_sku_option_ids.append(temp_spec.option_id)
            spec_sku_map[tuple(temp_sku_option_ids)] = temp_sku.id

        """3.组合 并找到sku_id 绑定"""
        spu_spec_qs = spu.specs.order_by('id')  # 获取当前spu中的所有规格

        for index, spec in enumerate(spu_spec_qs):  # 遍历当前所有的规格
            spec_option_qs = spec.options.all()  # 获取当前规格中的所有选项
            temp_option_ids = current_sku_option_ids[:]  # 复制一个新的当前显示商品的规格选项列表
            for option in spec_option_qs:  # 遍历当前规格下的所有选项
                temp_option_ids[index] = option.id  # [8, 12]
                option.sku_id = spec_sku_map.get(tuple(temp_option_ids))  # 给每个选项对象绑定下他sku_id属性

            spec.spec_options = spec_option_qs  # 把规格下的所有选项绑定到规格对象的spec_options属性上

        context = {
            'categories': get_categories(),  # 商品分类
            'breadcrumb': get_breadcrumb(category),  # 面包屑导航
            'sku': sku,  # 当前要显示的sku模型对象
            'category': category,  # 当前的显示sku所属的三级类别
            'spu': spu,  # sku所属的spu
            'spec_qs': spu_spec_qs,  # 当前商品的所有规格数据
        }
        return render(request, 'detail.html', context)


class DetailVisitView(View):
    """商品类别每日访问类统计"""

    def post(self,request,category_id):

        try:
            category = GoodsCategory.objects.get(id=category_id)
        except GoodsCategory.DoesNotExist:
            return http.HttpResponseForbidden('category_id')

        now_date = timezone.now() #获取当前时间日期对象

        try:
            goods_visit = GoodsVisitCount.objects.get(category=category,date=now_date)
        except GoodsVisitCount.DoesNotExist:
            # 如果此三级类型今天是第一次访问就新增地址
            goods_visit = GoodsVisitCount(
                category=category
            )

        #无论是新的还是旧的都做累加1
        goods_visit.count += 1
        goods_visit.save()

        return http.JsonResponse({'code':RETCODE.OK,'errmsg':'OK'})

meiduo_mall/apps/meiduo_admin/views.py
from django.shortcuts import render

# Create your views here.

meiduo_mall/apps/meiduo_admin/views/admin_views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import ListAPIView
from django.contrib.auth.models import Group

from users.models import User
from meiduo_admin.serializers.admin_serializer import *
from meiduo_admin.serializers.group_serializer import GroupSerializer
from meiduo_admin.pages import MyPage


class AdminView(ModelViewSet):
    queryset = User.objects.filter(is_staff=True)
    serializer_class = AdminSerializer
    pagination_class = MyPage


class GroupSimpleView(ListAPIView):
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

meiduo_mall/apps/meiduo_admin/views/channel_views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import ListAPIView

from meiduo_admin.serializers.channel_serializer import *
from goods.models import GoodsChannel
from meiduo_admin.pages import MyPage


class ChannelView(ModelViewSet):
    """商品频道"""
    queryset = GoodsChannel.objects.all()
    serializer_class = GoodsChannelSerializer
    pagination_class = MyPage


class CategoriesView(ListAPIView):
    """频道分类"""
    queryset = GoodsChannel.objects.all()
    serializer_class = GoodsChannelSerializer

meiduo_mall/templates/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>美多商城-购物车</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/host.js"></script>
	<script type="text/javascript" src="/static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="/static/js/axios-0.18.0.min.js"></script>
</head>
<body>
	<div id="app" v-cloak>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到美多商城!</div>
			<div class="fr">
                <div class="login_btn fl" v-if="username">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="/logout/" class="quit">退出</a>
                </div>
                <div class="login_btn fl" v-else>
                    <a href="/login/">登录</a>
                    <span>|</span>
                    <a href="/register/">注册</a>
                </div>
				<div class="user_link fl">
					<span>|</span>
					<a href="/info/">用户中心</a>
					<span>|</span>
					<a href="/carts/">我的购物车</a>
					<span>|</span>
					<a href="/orders/info/1/">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_wrap fl">
			<form method="get" action="/search/" class="search_con">
				<input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
			<ul class="search_suggest fl">
				<li><a href="#">索尼微单</a></li>
				<li><a href="#">优惠15元</a></li>
				<li><a href="#">美妆个护</a></li>
				<li><a href="#">买2免1</a></li>
			</ul>
		</div>
	</div>

	<div class="total_count">全部商品<em>[[total_count]]</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

	<ul class="cart_list_td clearfix" v-for="(sku,index) in carts">
		<li class="col01"><input type="checkbox" name="selected" v-model="sku.selected" @change="update_selected(index)"></li>
		<li class="col02"><img :src="sku.default_image_url"></li>
		<li class="col03">[[sku.name]]</li>
		<li class="col04">台</li>
		<li class="col05">[[sku.price]]元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" @click="on_add(index)">+</a>
				<input type="text" class="num_show fl" v-model="sku.count" autocomplete="off" @blur="on_input(index)">
				<a href="javascript:;" class="minus fl" @click="on_minus(index)">-</a>
			</div>
		</li>
		<li class="col07">[[sku.amount]]元</li>
		<li class="col08"><a href="javascript:;" @click="on_delete(index)">删除</a></li>
	</ul>

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" @change="on_selected_all" v-model="selected_all"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>[[total_selected_amount]]</em><br>共计<b>[[total_selected_count]]</b>件商品</li>
		<li class="col04"><a href="/orders/settlement/">去结算</a></li>
	</ul>
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	</div>
	<script>
        var cart_skus = {{ cart_skus | safe }};
    </script>
    <script type="text/javascript" src="/static/js/common.js"></script>
	<script type="text/javascript" src="/static/js/cart.js"></script>
</body>
</html>

meiduo_mall/templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>美多商城-我的订单</title>
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.pagination.css">
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/host.js"></script>
    <script type="text/javascript" src="/static/js/vue-2.5.16.js"></script>
    <script type="text/javascript" src="/static/js/axios-0.18.0.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
</head>
<body>
<div id="app" v-cloak>
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到美多商城!</div>
            <div class="fr">
                <div class="login_btn fl" v-if="username">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="/logout/" class="quit">退出</a>
                </div>
                <div class="login_btn fl" v-else>
                    <a href="/login/">登录</a>
                    <span>|</span>
                    <a href="/register/">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="/info/">用户中心</a>
                    <span>|</span>
                    <a href="/carts/">我的购物车</a>
                    <span>|</span>
                    <a href="/orders/info/1/">我的订单</a>
                </div>
            </div>
        </div>
    </div>

    <div class="search_bar clearfix">
        <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
        <div class="search_wrap fl">
            <form method="get" action="/search/" class="search_con">
                <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
            <ul class="search_suggest fl">
                <li><a href="#">索尼微单</a></li>
                <li><a href="#">优惠15元</a></li>
                <li><a href="#">美妆个护</a></li>
                <li><a href="#">买2免1</a></li>
            </ul>
        </div>
    </div>

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="/info/">· 个人信息</a></li>
                <li><a href="/orders/info/1/" class="active">· 全部订单</a></li>
                <li><a href="/addresses/">· 收货地址</a></li>
                <li><a href="/password/">· 修改密码</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in page_orders %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.create_time.strftime('%Y-%m-%d %H:%M:%S') }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                </ul>
                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for sku in order.sku_list %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ sku.default_image.url }}"></li>
                                    <li class="col02"><span>{{ sku.name }}</span><em>{{ sku.price }}元</em></li>
                                    <li class="col03">{{ sku.count }}</li>
                                    <li class="col04">{{ sku.amount }}元</li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_amount }}元<br>含运费：{{ order.freight }}元</td>
                        <td width="15%">{{ order.pay_method_name }}</td>
                        <td width="15%">
                            <a @click="oper_btn_click('{{ order.order_id }}', {{ order.status }})"
                               class="oper_btn">{{ order.status_name }}</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}
            <div class="pagenation">
                <div id="pagination" class="page"></div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</div>
<script type="text/javascript" src="/static/js/jquery.pagination.min.js"></script>
<script type="text/javascript" src="/static/js/common.js"></script>
<script type="text/javascript" src="/static/js/base.js"></script>
<script type="text/javascript" src="/static/js/user_center_order.js"></script>
<script>
    $(function () {
        $('#pagination').pagination({
            currentPage: {{ page_num }},
            totalPage: {{ total_page }},
            callback: function (current) {
                location.href = '/orders/info/' + current + '/';
            }
        })
    });
</script>

</body>
</html>